### ISSUE TITLE
Cannot install 2.4.0 ipfabric dependency in coordination with chatops and golden-config

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot-app-ssot#383] opened 2024-03-08 21:22 UTC
Would it be possible for someone to look into how to sync this app, nautobot-chatops, and golden-config with the latest ipfabric updates.  I am trying to build an image which includes all these apps together.

ip-fabric diagrams has been deprecated - https://pypi.org/project/ipfabric-diagrams/

Additionally, there is a problem with ipfabric and the dependency for `httpx`
SSOT lockfile has: https://github.com/nautobot/nautobot-app-ssot/blob/aecbf0f7e6a7859c1d0c8749832d51a8c5b49b08/poetry.lock#L2194

Golden-config lockfile has: https://github.com/nautobot/nautobot-app-golden-config/blob/5fbee9fd465d60749cdb0b7f2cd7e59afad5d771/poetry.lock#L2842

chatops lockfile has: https://github.com/nautobot/nautobot-app-chatops/blob/0e1250b6d9fdc2d63cb66f6321152466b9e17866/poetry.lock#L1904

**Comment by Kircheneer** [comment] 2024-03-18 07:21
So this means that the issue is addressed? @mattmiller87

**Comment by jdrew82** [comment] 2024-03-18 16:37
This is also addressed in #354.

**Comment by jdrew82** [comment] 2024-08-23 17:24
Closing as this has been addressed.

**Closed by jdrew82** 2024-08-23 17:24 UTC
Labels: status: accepted, type: housekeeping, integration: ipfabric
