### ISSUE TITLE
ACI Sync Job fails with TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by kingfetty** [nautobot/nautobot-app-ssot#479] opened 2024-07-10 16:03 UTC
### Environment
* Python version:  3.10.12
* Nautobot version:  2.2.7
* nautobot-ssot version:  2.6.1

### Expected Behavior
Expected to synchronize data from ACI fabric to NB instance

### Observed Behavior
Running the job connects to the ACI APIC and starts to pull data, upon reaching the load_devices code errors with the below stack trace:

`Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/store/__init__.py", line 155, in get_or_instantiate
    obj = self.get(model=model, identifier=ids)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/store/local.py", line 49, in get
    raise ObjectNotFound(f"{modelname} {uid} not present in {str(self)}")
diffsync.exceptions.ObjectNotFound: device_type N9K-C93180YC-FX3__ not present in LocalStore

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/integrations/aci/jobs.py", line 90, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 317, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 136, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/integrations/aci/jobs.py", line 75, in load_source_adapter
    self.source_adapter.load()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/integrations/aci/diffsync/adapters/aci.py", line 438, in load
    self.load_devices()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/integrations/aci/diffsync/adapters/aci.py", line 412, in load_devices
    self.get_or_instantiate(
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/__init__.py", line 813, in get_or_instantiate
    return self.store.get_or_instantiate(model=model, ids=ids, attrs=attrs)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/store/__init__.py", line 159, in get_or_instantiate
    obj = model(**ids, **attrs)
TypeError: 'str' object is not callable`

### Steps to Reproduce
Create nautobot install
Ensure SSOT[ACI] is installed and properly loaded with correct environmental variables
Enable sync job
Execute sync job against controller.

### Suspected Cause

Within the plugin code for the ACI adapter load_devices() is calling self.get_or_instantiate() passing a string in of "device_type" for the model argument.  Further in the code, diffsync is attempting to execute whatever this argument is as a method.  Given that string types are not callable it throws the error.  I suspect that get_or_instantiate is being called with incorrect argument as the "model" argument.

**Comment by kingfetty** [comment] 2024-07-10 16:21
After the correction of using a string to using self.device_type the code now fails at load_interfaces() because there is a block attempting to read the variable device_specs before it is assigned.  This is due to the fact that the variable is created inside an if block that checks if a yaml file exists and the reference to the variable is outside this if block.

**Comment by kingfetty** [comment] 2024-07-10 16:41
Also appears Sync Job is using default soft timeout limit of 5 minutes which is way too short for a sync job.  This should be updated in the jobs.py meta to be at least several hours.

**Comment by ShivaniMauryaIntel** [comment] 2024-07-16 11:00
I had the same issue. If the issue is fixed, do we need to reinstall the ssot plugin ?

**Comment by ShivaniMauryaIntel** [comment] 2024-07-16 12:11
@jdrew82 I have reinstalled the ssot plugin & ran the aci sync job again. The job is still failing & a new error is coming now - 
 "exc_message": [
        "ltd"]
 where "ltd" is the identifier used in my env variable. If I replace ltd with abc or any other name, that name will be the error.
 Below are the env vars used - 
 NAUTOBOT_APIC_BASE_URI_**LTD**
NAUTOBOT_APIC_USERNAME_**LTD**
NAUTOBOT_APIC_PASSWORD_**LTD**
NAUTOBOT_APIC_VERIFY_**LTD**
NAUTOBOT_APIC_SITE_**LTD**
NAUTOBOT_APIC_TENANT_PREFIX_**LTD**

**Comment by jdrew82** [comment] 2024-07-16 14:46
@ShivaniMauryaIntel can you provide the full traceback? Without knowing where this is happening it's tough to track down the cause.

**Comment by jdrew82** [comment] 2024-07-16 14:48
> Also appears Sync Job is using default soft timeout limit of 5 minutes which is way too short for a sync job. This should be updated in the jobs.py meta to be at least several hours.

The global timeout is defined with the `NAUTOBOT_CELERY_TASK_SOFT_TIME_LIMIT` and `NAUTOBOT_CELERY_TASK_TIME_LIMIT` environment variables as hard limits. You can go into the Job settings and set a lower timeout if desired. Although we can set one in the Job itself it's difficult to know an appropriate timeout as it will vary quite a bit depending upon your deployment size and size of dataset being imported.

**Comment by ShivaniMauryaIntel** [comment] 2024-07-18 10:16
@jdrew82 Based on your suggestion on slack,  I have defined my env vars in a .env file & called the file in nautobot service - https://josh-v.com/nautobot-environment-file/
Below are the env vars used -
NAUTOBOT_APIC_BASE_URI_LTD
NAUTOBOT_APIC_USERNAME_LTD
NAUTOBOT_APIC_PASSWORD_LTD
NAUTOBOT_APIC_VERIFY_LTD
NAUTOBOT_APIC_SITE_LTD
NAUTOBOT_APIC_TENANT_PREFIX_LTD

Now, I am running the ACI sync job from Nautobot UI & I am getting the error - 
**Return Data -** 
{
    "exc_message": [
        "ltd"
    ],
    "exc_module": "builtins",
    "exc_type": "KeyError"
}

**![7](https://github.com/user-attachments/assets/fbd248a4-38c3-4f7c-9018-018dc377dec8)** 
Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/aci/jobs.py", line 90, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 317, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 136, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/aci/jobs.py", line 74, in load_source_adapter
    self.source_adapter = AciAdapter(job=self, sync=self.sync, client=aci_creds[self.apic])
KeyError: 'ltd'

**Comment by jdrew82** [comment] 2024-08-23 16:59
@ShivaniMauryaIntel @kingfetty Can you confirm if this has been resolved with the recent updates to the ACI integration?

**Comment by ShivaniMauryaIntel** [comment] 2024-08-27 07:55
@jdrew82 I will test this in couple of days & will let you know.

**Comment by ShivaniMauryaIntel** [comment] 2024-09-10 11:08
@jdrew82 There is another issue now. I have upgraded the ssot package to 3.1.0. While running the aci sync job, there is no "ACI APIC" coming up in drop down -
![image](https://github.com/user-attachments/assets/a78100c8-b9ee-4899-b0cd-9b51eeee1897)
I have validated the APIC details are added as part of environment variable, & visible from nautobot shell -
![image](https://github.com/user-attachments/assets/afee730b-5bb4-42d5-a859-f5df0d677903)

This is the 2nd time when the issue is fixed by your team, however, in actual, the issue is not getting resolved in Production. Can you please perform end-to-end testing before releasing a new version? As a user, we are just reinstalling the package multiple times, performing testing, facing another error & raising a bug. This is going in a loop without any value. I hope you understand the pain points from user perspective.

**Comment by ShivaniMauryaIntel** [comment] 2024-09-10 13:29
@jdrew82  I have made the required changes to nautobot_config.py file. However, I still don't see any ACI APIC getting loaded in the dropdown menu.

**Comment by jdrew82** [comment] 2024-09-10 14:45
> @jdrew82 I have made the required changes to nautobot_config.py file. However, I still don't see any ACI APIC getting loaded in the dropdown menu.

I think you misunderstood my last comment. The code that pulls the configuration from nautobot_config.py is no longer in place. You must create the ExternalIntegration and Controller objects manually inside the Nautobot UI. The installation instructions for ACI denote the required pieces for ACI in the ExternalIntegration.

**Comment by ShivaniMauryaIntel** [comment] 2024-09-10 15:40
Can you share a document to install ExternalIntegration object as I don't see it in the Nautobot UI? I am on Nautobot version 2.3.2

**Comment by jdrew82** [comment] 2024-09-10 17:41
@ShivaniMauryaIntel You can find ExternalIntegration under the Extensibility menu. Unfortunately, we don't have screenshots showing the process with the ACI integration but we do have some images and documentation on the ExternalIntegration portion in the Device42 [documentation](https://docs.nautobot.com/projects/ssot/en/latest/admin/integrations/device42_setup/#configuration). The only piece you'd need to do after that is to create a Controller object that references that ExternalIntegration. You can find those under the Devices menu.

**Comment by ShivaniMauryaIntel** [comment] 2024-09-12 11:04
Hi @jdrew82  I have added the ACI as part of ExternalIntegration & created a Controller object to reference it. However, while running the job, I am getting the error Undefined environment variable - 
![image](https://github.com/user-attachments/assets/2522ff60-e76a-4ffe-8826-2e5c5529bbd5)

I have validated both username & password from NB shell & they are showing up -
![image](https://github.com/user-attachments/assets/306f7e2a-ecf3-41cb-b2b2-284e2b8f914c)

Even after adding the password as secret, it is getting verified -
![image](https://github.com/user-attachments/assets/ad1f33de-a515-4563-8f36-6cd4c389c945)

What can be the issue here?

**Comment by jdrew82** [comment] 2024-09-12 11:26
@ShivaniMauryaIntel Can you confirm that the environment variable is also available to the worker process? If you're deploying with service files, ie systemd, then I suggest using an EnvironmentFile that's shared by both processes. If you're using containers just make sure that both nautobot and worker containers are getting the same env file.

**Comment by ShivaniMauryaIntel** [comment] 2024-09-12 12:12
Ok, I have now shared environmentfile with both process. Now, I am getting below error -
![image](https://github.com/user-attachments/assets/bf3a0497-3d1f-421d-8ff8-bd7ba2433748)

FYI - I am using a signed certificate by trusted authority for Nautobot server. 
I have not modified the default location of the cert & key files. My cert file is under - /etc/pki/tls/certs/ & the key file is under - /etc/pki/tls/private. Also, the nautobot UI is working with this SSL certificate.

**Comment by jdrew82** [comment] 2024-09-12 12:15
It looks like an SSL verification error for an internal site. You need to ensure that you have the CA cert and private key for that site installed and trusted. This is fairly standard when working with internal CA protected sites.

**Comment by ShivaniMauryaIntel** [comment] 2024-09-13 05:56
Another error with ACI job -
![image](https://github.com/user-attachments/assets/34f05ad3-d3f3-45a3-8f18-e5cffc87d6d9)

I have the Controller associated with Managed Device Group -
![image](https://github.com/user-attachments/assets/7c481906-66ab-418a-bd7e-8731abdea9b9)

**Comment by jdrew82** [comment] 2024-09-15 16:14
Actually, I think I might have spotted an issue [here](https://github.com/nautobot/nautobot-app-ssot/blob/091fb3a66c8c1410f4ef67d05328387efaed191b/nautobot_ssot/integrations/aci/diffsync/adapters/aci.py#L438).

**Closed** 2024-09-16 12:54 UTC
Labels: type: bug, integration: ciscoaci

**Comment by ShivaniMauryaIntel** [comment] 2024-09-19 10:52
@jdrew82  Did you push this code changes to the main branch? As I uninstalled & installed ssot[aci] plugin again, & everytime the older code is getting installed - 
![image](https://github.com/user-attachments/assets/fcb13bc4-5ac6-4c8e-8ede-1290d6797439)

I can see that the main branch doesn't have this code change.
