### ISSUE TITLE
v2 Crash when loading 2 locations with the same name

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot-app-ssot#268] opened 2023-11-07 14:04 UTC
### Environment
* Python version:   3.11.4
* Nautobot version:   2.0.0
* nautobot-ssot version:   2.0.0

### Expected Behavior
Both location to get added in to Nautobot.

### Observed Behavior
When adding two Locations of differing Location Types, with one Location a Parent and the other a Child, the job errors out if they share the same name.

For example:
If you have Location Types: Country --> State --> City
Then try adding in a Location of type State with the name "Indiana", followed by a Location of type City with the name "Indiana" and the parent of that is the State "Indiana", it will error out.
 

### Steps to Reproduce
1. See example above in "Observed Behavior".  Example code is below for the remote adapter portion

```
country_name = "USA"
state_name = "Indiana"
city_name = "Indiana"

new_location = self.location(
    name=state_name,
    status="Active",
    location_type="State",
    parent__name=country_name,
    pk=None,
)
self.add(new_location)

new_location = self.location(
    name=city_name,
    status="Active",
    location_type="City",
    parent__name=state_name,
    pk=None,
)
self.add(new_location)
```

Throws this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 322, in run
    self.sync_data(memory_profiling)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 136, in sync_data
    self.load_source_adapter()
  File "/source/nautobot_ssot_mulesoft/jobs.py", line 125, in load_source_adapter
    self.source_adapter.load()
  File "/source/nautobot_ssot_mulesoft/diffsync/adapters/csv.py", line 125, in load
    self.add(new_location)
  File "/usr/local/lib/python3.11/site-packages/diffsync/__init__.py", line 770, in add
    return self.store.add(obj=obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffsync/store/local.py", line 107, in add
    raise ObjectAlreadyExists(f"Object {uid} already present", obj)
diffsync.exceptions.ObjectAlreadyExists: ('Object Indiana already present', location "Indiana")

```

**Comment by Kircheneer** [comment] 2023-11-20 11:56
Can you share the model code? My suspicion is that you need to add in another identifier next to the `name` field if your identifier is duplicated within your data set.

**Comment by matt852** [comment] 2023-11-20 12:53
I was able to work around this in my specific situation, as Country, State, and City (Parent's Parent, Parent, and Child) make a unique set when combined, whereas State and City (Parent and Child) are not always unique.
The workaround is to reference all 3 layers in my diffsync adapter, like so:
```python
new_location = self.location(
    name=city_name,
    status="Active",
    location_type="City",
    parent__name=state_name,
    parent__parent__name=country_name,
    pk=None,
)```

Then in the base model for Location, update the identifier as:

```python
_identifiers = ("name", "parent__name")
```

And add `"parent__parent__name"` to `_attributes`.


While this works, maybe we can catch the exception with a specific log message instead of the traceback, even if it's just this error message returned?

**Comment by jdrew82** [comment] 2024-04-17 14:17
I think this is a "works as intended" as this is a limitation of core Nautobot. Closing.

**Closed by jdrew82** 2024-04-17 14:17 UTC
Labels: wontfix, integration: contrib
