### ISSUE TITLE
ARISTACV Loading data from Nautobot fails

### ISSUE THREAD

**Issue by gerardocastaldo** [nautobot/nautobot-app-ssot#266] opened 2023-11-05 11:42 UTC
### Environment
* Python version:  3.10
* Nautobot version:  2.0.3
* nautobot-ssot version:  2.0.0

### Observed Behavior
During the "Loading data from Nautobot" jobs i receive this error

```
Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 322, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 145, in sync_data
    self.load_target_adapter()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/jobs.py", line 113, in load_target_adapter
    self.target_adapter.load()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 140, in load
    self.load_ip_addresses()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 92, in load_ip_addresses
    for ipaddr in OrmIPAddress.objects.filter(interface__device__device_type__manufacturer__name="Arista"):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/ipam/querysets.py", line 450, in filter
    return super().filter(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/models/querysets.py", line 86, in filter
    return super().filter(*args, **self.split_composite_key_into_kwargs(composite_key, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'interface' into field. Choices are: _custom_field_data, bgp_peer_endpoints, bgp_peer_groups, bgproutinginstance, created, description, destination_for_associations, dns_name, host, id, interface_redundancy_groups, interfaces, ip_version, last_updated, mask_length, nat_inside, nat_inside_id, nat_outside_list, parent, parent_id, primary_ip4_for, primary_ip6_for, role, role_id, services, source_for_associations, status, status_id, tagged_items, tags, tenant, tenant_id, type, vm_interfaces
```

![Uploading screencapture-10-44-141-39-8080-plugins-ssot-history-29e3c75d-5b68-41db-b13a-687bb372bd38-jobresult-2023-11-05-12_41_31.png…]()

### Steps to Reproduce
1. sync data from CVaaS

**Comment by glennmatthews** [comment] 2023-11-06 14:35
Looks like this is due to the 1.x-to-2.x core data model change from `IPAddress.interface` (single FK) to `IPAddress.interfaces` (M2M) not being accounted for in the app.

**Comment by erjac77** [comment] 2023-11-08 19:34
We hit this bug too :(

**Comment by Kircheneer** [comment] 2023-11-20 12:06
From what I see the fix might just be to change this query

```
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 92, in load_ip_addresses
    for ipaddr in OrmIPAddress.objects.filter(interface__device__device_type__manufacturer__name="Arista"):
```

to

```
    for ipaddr in OrmIPAddress.objects.filter(interfaces__device__device_type__manufacturer__name__in=["Arista"]):
```

**Comment by gerardocastaldo** [comment] 2023-11-21 14:53
I applied the change suggested by Kirchner and the issue about the interface is disappeared but the new one is appeared.

Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 322, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 145, in sync_data
    self.load_target_adapter()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/jobs.py", line 113, in load_target_adapter
    self.target_adapter.load()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 138, in load
    self.load_devices()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 45, in load_devices
    version=nautobot.get_device_version(dev),
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/utils/nautobot.py", line 84, in get_device_version
    software_relation = Relationship.objects.get(name="Software on Device")
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/models/querysets.py", line 86, in filter
    return super().filter(*args, **self.split_composite_key_into_kwargs(composite_key, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: advanced_ui, created, description, destination_filter, destination_hidden, destination_label, destination_type, destination_type_id, id, key, label, last_updated, relationship_associations, required_on, source_filter, source_hidden, source_label, source_type, source_type_id, type

**Comment by Kircheneer** [comment] 2023-11-22 08:19
I think we have a similar thing here, `Relationship.name` was moved to `Relationship.label`. So changing

```
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/utils/nautobot.py", line 84, in get_device_version
    software_relation = Relationship.objects.get(name="Software on Device")
```

to

```
    software_relation = Relationship.objects.get(label="Software on Device")
```

could be a fix. @gerardocastaldo thank you for trying this out - if you have the time please submit a pull request once this is working. Thank you!

**Comment by gerardocastaldo** [comment] 2023-11-22 12:55
Hi @Kircheneer, with these changes the job works but it doesn't synchronize the configurations. The job reports that it was executed in dry-run mode. When in doubt, I ran it 4 times without select the dry-run checkbox and the result is always the same.

Do you have any idea ?

![image](https://github.com/nautobot/nautobot-plugin-ssot/assets/48739169/be59d8c2-e7dd-4319-8d3a-743667cf3736)

**Comment by gerardocastaldo** [comment] 2023-11-24 09:41
Hi everyone, has anyone found if there is any reason why the plugin always runs in dry-run mode?

Thanks in advance

**Comment by jdrew82** [comment] 2023-11-27 23:16
@gerardocastaldo I've added PR #282 to fix the dry-run issue you discovered. Once that is merged we just need you to rebase your PR for #279.

**Comment by gerardocastaldo** [comment] 2023-11-28 19:43
Hi @Kircheneer and @jdrew82 ,

I executed the job and now the estractions from cloudvision and nautobot works fine but the sync process fails.

I had think that I didn't assigned a variable but, after few checks,  I don't see errors in configuration.

Follows the traceback.

```

Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/utils/nautobot.py", line 26, in verify_site
    site_obj = Location.objects.get(name=site_name, location_type=loc_type)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
nautobot.dcim.models.locations.Location.DoesNotExist: Location matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 322, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 166, in sync_data
    self.execute_sync()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 98, in execute_sync
    self.source_adapter.sync_to(self.target_adapter, flags=self.diffsync_flags)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/__init__.py", line 601, in sync_to
    return target.sync_from(self, diff_class=diff_class, flags=flags, callback=callback, diff=diff)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/__init__.py", line 573, in sync_from
    result = syncer.perform_sync()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 329, in perform_sync
    changed |= self.sync_diff_element(element)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 379, in sync_diff_element
    changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 428, in sync_model
    dst_model = self.model_class.create(diffsync=self.dst_diffsync, ids=ids, attrs=attrs)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py", line 56, in create
    site = nautobot.verify_site(APP_SETTINGS.get("from_cloudvision_default_site", DEFAULT_SITE))
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/utils/nautobot.py", line 33, in verify_site
    site_obj.validated_save()
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/models/__init__.py", line 118, in validated_save
    self.full_clean()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'name': ['This field cannot be blank.']}

```

Have you an idea ?

Other small problem. When the job finished the status is always green although if it ends with an error.

![image](https://github.com/nautobot/nautobot-plugin-ssot/assets/48739169/53685b55-66cb-4576-9573-c24a79568b9e)


Thanks in advance.

**Comment by jdrew82** [comment] 2023-11-28 19:55
This error is due to not having your settings right for the App. It's required to have the following settings defined:

- aristacv_from_cloudvision_default_site
- aristacv_from_cloudvision_default_device_role
- aristacv_from_cloudvision_default_device_role_color

Each of these settings defines the default to use when loading Devices. Specifically you hit the default_site missing as shown towards the bottom of your traceback and indicated by the name being blank in the ValidationError. Please ensure that you define those variables, rebuild your environment, and re-run the Job.

**Comment by gerardocastaldo** [comment] 2023-11-30 11:43
Hi @jdrew82 , I configured the variables that you wrote me but i receive another error about the "device_role" and i don't think is another my mistake.

Follows I report the ssot configuration and the traceback 

Thanks in advance


```
PLUGINS_CONFIG = {
    "nautobot_ssot": {
        "enable_aristacv": True,
        "aristacv_cvp_token": os.getenv("NAUTOBOT_ARISTACV_TOKEN", ""),
        "aristacv_cvaas_url": os.getenv("NAUTOBOT_ARISTACVAAS_URL", "www.arista.io:443"),
        "aristacv_cvp_host": os.getenv("NAUTOBOT_ARISTACV_HOST", ""),
        "aristacv_cvp_port": os.getenv("NAUTOBOT_ARISTACV_PORT", 443),
        "aristacv_cvp_user": os.getenv("NAUTOBOT_ARISTACV_USERNAME", ""),
        "aristacv_cvp_password": os.getenv("NAUTOBOT_ARISTACV_PASSWORD", ""),
        "aristacv_verify": is_truthy(os.getenv("NAUTOBOT_ARISTACV_VERIFY", True)),
        "aristacv_delete_devices_on_sync": is_truthy(os.getenv("NAUTOBOT_ARISTACV_DELETE_ON_SYNC", False)),
        "aristacv_apply_import_tag": is_truthy(os.getenv("NAUTOBOT_ARISTACV_IMPORT_TAG", False)),
        "aristacv_import_active": is_truthy(os.getenv("NAUTOBOT_ARISTACV_IMPORT_ACTIVE", False)),
        "aristacv_create_controller": is_truthy(os.getenv("NAUTOBOT_ARISTACV_CREATE_CONTROLLER", False)),
        "aristacv_controller_site": os.getenv("NAUTOBOT_ARISTACV_CONTROLLER_SITE", ""),
        "aristacv_from_cloudvision_default_device_role": "network",
        "aristacv_from_cloudvision_default_device_role_color": "ff0000",
        "aristacv_from_cloudvision_default_site": "cloudvision_imported",
        "aristacv_import_active": is_truthy(os.getenv("NAUTOBOT_ARISTACV_IMPORT_ACTIVE", False))
    },
    "nautobot_bgp_models": {
        "default_statuses": {
            "AutonomousSystem": ["active", "available", "planned"],
            "Peering": ["active", "decommissioned", "deprovisioning", "offline", "planned", "provisioning"]
        }
    },
    "nautobot_firewall_models": {
        "default_status": "active",
        "allowed_status": [],
        "capirca_remark_pass": True,
        "capirca_os_map": {
            "cisco_ios": "cisco",
            "arista_eos": "arista"
        }
    }
}

```



```
Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 322, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 166, in sync_data
    self.execute_sync()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 98, in execute_sync
    self.source_adapter.sync_to(self.target_adapter, flags=self.diffsync_flags)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/__init__.py", line 601, in sync_to
    return target.sync_from(self, diff_class=diff_class, flags=flags, callback=callback, diff=diff)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/__init__.py", line 573, in sync_from
    result = syncer.perform_sync()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 329, in perform_sync
    changed |= self.sync_diff_element(element)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 379, in sync_diff_element
    changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 428, in sync_model
    dst_model = self.model_class.create(diffsync=self.dst_diffsync, ids=ids, attrs=attrs)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py", line 78, in create
    new_device = OrmDevice(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 503, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: Device() got an unexpected keyword argument 'device_role'

```

**Comment by jdrew82** [comment] 2023-11-30 13:06
Yeah... I see the problem. 🤦‍♂️ I thought we had caught all of those changes but I guess not. I'll get a fix pushed in a bit.

**Comment by gerardocastaldo** [comment] 2023-12-04 12:02
Hi @jdrew82 ,

I found the error but, resolved these, I have another problem that I don't understand how to solve.

Here you see the resolution

![image](https://github.com/nautobot/nautobot-plugin-ssot/assets/48739169/c1896e0d-5309-4a56-8b9a-61f931d7cc1f)



The traceback reports the issue about the creation of the ip address but the problem is that the device hasn't been create for problem to map the location and role.

![image](https://github.com/nautobot/nautobot-plugin-ssot/assets/48739169/7e34be51-1c3a-4b5c-9a88-01eadf7a799b)

![image](https://github.com/nautobot/nautobot-plugin-ssot/assets/48739169/e68bd7c2-fc7d-49fe-816c-9a64546fb166)

The role with the UUID 8ea3ff5d-625f-451c-83fa-7197e8c7c987 is defined

![image](https://github.com/nautobot/nautobot-plugin-ssot/assets/48739169/027c79b3-e179-44c8-8f2d-36453b7dfe5c)

**Comment by jdrew82** [comment] 2023-12-07 22:14
@gerardocastaldo I believe the issue is that the Site LocationType doesn't have the Device ContentType associated with it. Same with Role. I've gone ahead and pushed a fix in #299.

**Comment by jdrew82** [comment] 2023-12-08 15:13
@gerardocastaldo please confirm you're no longer having issues. If you are, we can reopen this.

**Comment by gerardocastaldo** [comment] 2023-12-09 16:18
Hi @jdrew82 , I'm sorry but our work isn't finished.

I create the PR #301 to resolve other issues but the checks failing. Can you verify ?

Now I have another problem that i don't understand about the ip address creation.

```
Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 322, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 166, in sync_data
    self.execute_sync()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 98, in execute_sync
    self.source_adapter.sync_to(self.target_adapter, flags=self.diffsync_flags)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/__init__.py", line 601, in sync_to
    return target.sync_from(self, diff_class=diff_class, flags=flags, callback=callback, diff=diff)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/__init__.py", line 573, in sync_from
    result = syncer.perform_sync()
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 329, in perform_sync
    changed |= self.sync_diff_element(element)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 379, in sync_diff_element
    changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/diffsync/helpers.py", line 428, in sync_model
    dst_model = self.model_class.create(diffsync=self.dst_diffsync, ids=ids, attrs=attrs)
  File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py", line 246, in create
    new_ip.validated_save()
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/models/__init__.py", line 118, in validated_save
    self.full_clean()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'parent': ['Either a parent or a namespace must be provided.']}`

```

**Comment by jdrew82** [comment] 2023-12-09 19:59
That error is because there is now a requirement in 2.x to specify the parent Prefix for an IPAddress or the Namespace so it can figure out the parent Prefix. I'll have to look at the code again to see if we're grabbing those and can associate them or not. Thank you for the PR btw. If you can supply any examples of the data that is returned from the API calls in that PR so we can improve our tests that would be greatly appreciated.

**Comment by jdrew82** [comment] 2024-04-17 14:18
@gerardocastaldo is this still an issue or can we close it out?

**Closed** 2024-04-19 08:41 UTC
Labels: status: accepted, type: bug, integration: cloudvision
