### ISSUE TITLE
DryRun fail for Arista CVP

### ISSUE THREAD

**Issue by ksoufan** [nautobot/nautobot-app-ssot#606] opened 2024-11-21 16:40 UTC
### Environment
* Python version:  
* Nautobot version:  
* nautobot-ssot version:  

### Expected Behavior
Dryrun to sync with Arista CVP to be successful

### Observed Behavior
the run failed, Arista CVP added the ability to add Arista Access point and non-Arista device to their inventory list which causing the run to fail with below error
Unable to determine chassis type for Arista_0363EF_W118 so will be unable to retrieve interfaces.

### Steps to Reproduce
1. Add Arista APs or 3rd party devices
2. Initiate DryRun
3.

**Comment by ksoufan** [comment] 2024-11-26 19:31
Error showing as 
{
    "exc_message": [
        "module 'distutils' has no attribute 'util'"
    ],
    "exc_module": "builtins",
    "exc_type": "AttributeError"
}

**Comment by jdrew82** [comment] 2024-12-02 18:19
This appears to be a duplicate of #492 so closing.

**Closed by jdrew82** 2024-12-02 18:19 UTC
